name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sh-checker:
    name: sh-checker
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: run sh-checker
      uses: luizm/action-sh-checker@883217215b11c1fabbf00eb1a9a041f62d74c744 # v0.10.0
      with:
        sh_checker_shellcheck_disable: true
        sh_checker_shfmt_disable: true

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: conventional commits
      uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2

  codespell:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: Codespell
      uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2

  typos:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: typos
      uses: crate-ci/typos@9c74bdf21a6753329fcf7c44f6783cbe34057edd # master
